// <auto-generated />
using CozyThings.Services.ProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozyThings.Services.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CozyThings.Services.ProductApi.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CategoryName = "Chairs",
                            Description = "Some unique description #1...",
                            ImageUrl = "https://cozythings.blob.core.windows.net/cozythings/BCN__courtesy_Knoll.jpg",
                            Name = "Ultra Comfy X-Model",
                            Price = 99.980000000000004
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Sofas",
                            Description = "Some unique description #2...",
                            ImageUrl = "https://cozythings.blob.core.windows.net/cozythings/20-12-2022%2018-24-48.jpg",
                            Name = "Mega Comfy Y-Model",
                            Price = 1099.98
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Tables",
                            Description = "Some unique description #3...",
                            ImageUrl = "https://cozythings.blob.core.windows.net/cozythings/table-de-repas-design-bois-%C2%A9-17.jpg",
                            Name = "Super Comfy M-Model",
                            Price = 999.98000000000002
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Tables",
                            Description = "Some unique description #4...",
                            ImageUrl = "https://cozythings.blob.core.windows.net/cozythings/1580774388-16629622_master.jpg",
                            Name = "Giga Comfy R-Model",
                            Price = 1299.98
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
